### ISSUE TITLE
Actually packages got updates. Issues with new packages

### ISSUE THREAD

**Issue by Scottvishnu** [Brikwerk/nxbt#6] opened 2021-01-01 18:52 UTC
Hello,

I installed nxbt and got problems. 
demo and tui works without issue.
webapp has the Error:
The client is using an unsupported version of the Socket.IO or Engine.IO protocols

_(29307) accepted ('192.168.1.2', 50146)
192.168.1.2 - - [01/Jan/2021 13:32:40] "GET / HTTP/1.1" 200 10876 0.018651
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
192.168.1.2 - - [01/Jan/2021 13:32:40] "GET /socket.io/?EIO=3&transport=polling&t=NQzxuHt HTTP/1.1" 400 219 0.000838
192.168.1.2 - - [01/Jan/2021 13:32:40] "GET /favicon.png HTTP/1.1" 200 27202 0.003434
192.168.1.2 - - [01/Jan/2021 13:32:41] "GET /socket.io/?EIO=3&transport=polling&t=NQzxuXe HTTP/1.1" 400 219 0.000564
192.168.1.2 - - [01/Jan/2021 13:32:43] "GET /socket.io/?EIO=3&transport=polling&t=NQzxv9T HTTP/1.1" 400 219 0.000427
192.168.1.2 - - [01/Jan/2021 13:32:47] "GET /socket.io/?EIO=3&transport=polling&t=NQzxv_c HTTP/1.1" 400 219 0.000654
192.168.1.2 - - [01/Jan/2021 13:32:52] "GET /socket.io/?EIO=3&transport=polling&t=NQzxxD- HTTP/1.1" 400 219 0.000599_

If i open the website, i got a page but i can't interact with.

I tried to update all relevant files. But still got the same error.
After all, i install previous packages after i removed(flask-socketio python-socketio python-engineio).
pip3 install "Flask-SocketIO<5"
pip3 install "python-socketio<5"

Only a temporary fix for me (and others if someone try to run it.)
Hope i am not the only one.

**Comment by Brikwerk** [comment] 2021-01-01 23:59
Hi @Scottvishnu, thanks for posting an issue about this. I've had a chance to look into the problem and these errors are caused by Socket.IO (and other related dependencies) updating to support v5 of the Socket.IO protocol. This was a breaking change, thus, the v4 client (which nxbt uses) was incompatible, causing errors.

I've updated nxbt to support the new v5 protocol in the dev branch and pinned the version so this error shouldn't occur with future Socket.IO protocol updates. Before pushing these changes to pypi, would you be able to test the updated version of nxbt? This should be a fairly simple process (instructions below):

1. Uninstall the pypi variant of nxbt: `sudo pip3 uninstall nxbt`
2. Install the updated variant from the GitHub repo: `sudo pip3 install git+https://github.com/Brikwerk/nxbt.git@590e051e4b605bcc004b56fa0925ead60b281811`
3. Try running the webapp again: `sudo nxbt webapp`

Let me know if this works!

**Comment by Scottvishnu** [comment] 2021-01-02 11:54
For me it's now works with the new updates.
Thank you.
I am happy to support this project 👍 
I have some ideas for the project.

**Comment by Scottvishnu** [comment] 2021-01-02 12:07
For me it's now works with the new updates.
Thank you.
I am happy to support this project 👍
I have some ideas for the project.

**Comment by Brikwerk** [comment] 2021-01-02 21:49
Excellent, thanks again for bringing this to my attention. I've incorporated the bug fixes/version bumps into the latest release. This should be available on PyPi now (v0.1.3). If you have ideas for the project, feel free to post in the discussions section or create a new idea issue. With that, I think we can close this issue.

**Closed by Brikwerk** 2021-01-02 21:49 UTC
